version: 2
updates:
  - package-ecosystem: 'github-actions'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: 'daily'
