#!/usr/bin/env bash

set -euo pipefail

# Load the compat helpers. These ensure that we have a modern version of bash
# installed
source ./framework/compat

# Run framework in a subshell which should cause it to use homebrew bash rather
# than (what may be) the macos system bash.
./framework/framework


# TODO reload current shell to 1. run init scripts 2. get correct version of
# shell (e.g. /usr/bin/bash instead of /bin/bash). Reminder that framework ran
# in a subshell so nothing it did impacts this terminal session
# Maybe determine user's default shell and use that?
# exec SHELL_NAME will replace the current shell
