#!/usr/bin/env bash

dotfiles_homebrew_core_apply () {
  if ! command -v brew >/dev/null 2>&1; then
    if [ "$DOTFILES_HOMEBREW_SKIP" -eq 1 ]; then
      error 'This appears to be your first run of dotfiles. While homebrew can be skipped on '
      error 'subsequent runs, dotfiles cannot work without a core set of dependencies. Please'
      error 'rerun.'
      return 1
    fi

    log "Homebrew not found. Installing"

    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    brew analytics off

    log "Homebrew installed"
  fi

  # There's no good spot to put this, but we're almost certainly going to need
  # it at some point, so we might as well include it in core.
  #
  # Found this test on
  # https://forum.latenightsw.com/t/possible-for-a-script-to-test-whether-rosetta-2-is-installed/3207/2
  # where others verified that it works as intended.
  if [[ "$(pkgutil --files com.apple.pkg.RosettaUpdateAuto)" == "" ]]; then
    log 'Rosetta 2 is not installed. Installing it now.'
    sudo softwareupdate --install-rosetta --agree-to-license
  else
    log 'Rosetta 2 is already installed.'
  fi
}
