#!/usr/bin/env bash

dotfiles_vim_apply () {
  if [ "$DOTFILES_AIRPLANE_MODE" != '1' ]; then
    local BASE
    BASE="$(environment_get_path all home/.vim/bundle)"
    mkdir -p "$BASE"

    rm -rf "$BASE/vim-javascript-syntax"
    git clone --depth=1 https://github.com/jelera/vim-javascript-syntax.git "$BASE/vim-javascript-syntax"

    rm -rf "$BASE/vim-colors-solarized"
    git clone --depth=1 https://github.com/altercation/vim-colors-solarized.git "$BASE/vim-colors-solarized"

    rm -rf "$BASE/editorconfig"
    git clone --depth=1 https://github.com/editorconfig/editorconfig-vim.git "$BASE/editorconfig"
  fi
}
