#!/usr/bin/env bash

dotfiles_homedir_apply () {
  _apply () {
    local candidate
    candidate="$(environment_get_path "$CURRENT_ENVIRONMENT" home)"
    if [ -d "$candidate" ]; then
      debug "Rsyncing $candidate to $HOME"
      rsync --exclude ".DS_Store" --exclude ".git/" -av "$candidate/" "$HOME"
    fi
  }

  environment_map_func _apply

  # $$ is the current shell pid; this should tell us what shell we're currently
  # running so we can reload the right config file
  case $(ps -p $$) in
    *zsh*)
      debug 'reloading zsh'
      exec zsh
      ;;
    *bash*)
      debug 'reloading bash'
      exec bash
      ;;
  esac
}
