#!/usr/bin/env bash

# Note: framework and compat are the only files that should do stuff
# automatically. Since everything else gets sourced into this process, weird
# things can happen.

set -euo pipefail

pushd framework
source ./config
source ./logging
source ./util

source ./plugin
popd

# this'll be improved later, but for now, hardcoding solves some early issues
export DOTFILES_ENV=default

config_load
plugin_load_all
plugin_configure_all

plugin_run_plugins
