#!/usr/bin/env bash

set -euo pipefail

array_contains () {
  local -n haystack=$1
  local needle=$2

  for item in "${haystack[@]}"; do
    if [ "$item" == "$needle" ]; then
      return 0
    fi
  done

  return 1
}
