#!/usr/bin/env bash

# Make vim the default editor.
export EDITOR='vim'

# Set bash history to unlimited
export HISTFILESIZE=
export HISTSIZE=
# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth'
# Hide commands from history that are unlikely to ever be helpful
export HISTIGNORE="ls:pwd:date:git reset HEAD^"

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

# Avoid issues with `gpg` as installed via Homebrew.
# https://stackoverflow.com/a/42265848/96656
export GPG_TTY
GPG_TTY=$(tty)

# Enable DIRCOLORS the OSX way
# OSX uses LSCOLORS and Linux uses LS_COLORS.  While this repo is specific to
# OSX, the Linux form is assigned here to make it available to SendEnv in SSH.
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
export LS_COLORS="$LSCOLORS"
