#!/usr/bin/env bash

export DOTFILES_ADOBE_DEPS=('homebrew')
export DOTFILES_ADOBE_PLATFORMS=('darwin')

dotfiles_adobe_apply () {
  if [ -d '/Applications/Adobe Creative Cloud' ]; then
    debug 'Adobe Creative Cloud already installed'
    return 0
  fi

  local installer_path
  installer_path='/usr/local/Caskroom/adobe-creative-cloud/latest/Creative Cloud Installer.app'
  if [ ! -f "$installer_path" ]; then
    debug 'Adobe Installer not present. Assuming it was removed by a custom Brewfile'
    return 0
  fi

  open "$installer_path"

  remind 'Sign into Adobe Creative Cloud'
  remind 'Install Photoshop'
  remind 'Install Lightroom'
}

