# This Brewfile contains packages that must be installed for the dotfiles
# process to work. You cannot override this environment.

cask_args appdir: '/Applications'

tap 'caskroom/cask'

brew 'bash'
brew 'bash-completion@2'

# Enable Mac App Store (`mas`) entries in Brewfile
brew 'mas'

#
# Plugin: commitsigning
#

brew 'gnupg'
brew 'pinentry-mac'

#
# Plugin: ntfy
#

brew 'yq'

#
# Plugin: nvm
#

brew 'jq'
