#!/usr/bin/env bash

export DOTFILES_NTFY_CONFIG=('enable' 'pushover_key')

export DOTFILES_NTFY_DEPS=('homebrew')

_dotfiles_ntfy_ensure () {
  if ! command -v pip3 > /dev/null 2>&1; then
    echo 'The ntfy plugin requires python3. Please add it to your Brewfile'
    return 1
  fi

  if ! command -v ntfy > /dev/null 2>&1; then
    pip3 install git+https://github.com/ianwremmel/ntfy@multi-screenlock
    eval "$(ntfy shell-integration)"
  fi
}

dotfiles_ntfy_prompt_string () {
  case $1 in
    enable)
      echo 'Do you want to use ntfy? (1 for yes, 0 for no)'
      return 0
      ;;
    pushover_key)
      echo 'Enter your pushover API key'
      return 0
      ;;
    esac
  return 1
}

dotfiles_ntfy_apply () {
  debug 'checking if we want ntfy'
  if [ "$(plugin_config_get ntfy enable)" -ne "1" ]; then
    debug 'we do not want ntfy'
    return 0
  fi

  debug 'we want ntfy'

  _dotfiles_ntfy_ensure

  touch "$HOME/.ntfy.yml"

  if [ "$(wc -c < "$HOME/.ntfy.yml" | tr -d '[:space:]')" == "0" ]; then
    debug 'Initializing .ntfy.yml'
    echo 'backends:' > "$HOME/.ntfy.yml"
  fi

  # If the pushover key doesn't match what's in ntfy.yml, update it
  if [ "$(yq e .multi.locked.pushover.user_key "$HOME/.ntfy.yml")" != "$(plugin_config_get ntfy pushover_key)" ]; then
    debug 'Setting ntfy pushover key'
    yq eval --inplace ".multi.locked.pushover.user_key = \"$(plugin_config_get ntfy pushover_key)\"" "$HOME/.ntfy.yml"
  fi

  # Clear the unfocused behavior
  if [ "$(yq e .multi.unfocused.default "$HOME/.ntfy.yml")" != '{}' ]; then
    debug 'Setting ntfy unfocused behavior'
    yq eval --inplace ".multi.unfocused.default = {}" "$HOME/.ntfy.yml"
  fi

  # Clear the unfocused behavior
  if [ "$(yq e .multi.focused "$HOME/.ntfy.yml")" != '{}' ]; then
    debug 'Setting ntfy focused behavior'
    yq eval --inplace ".multi.focused.default = {}" "$HOME/.ntfy.yml"
  fi

  # Set default backend
  if ! yq e .backends "$HOME/.ntfy.yml" | grep -cq multi ; then
    debug 'Setting multi as ntfy backend'
    yq eval --inplace '.["backends"] += ["multi"]' "$HOME/.ntfy.yml"
  fi

  ntfy send "ntfy is installed and allowed to use Catalina's notification system"
}
