tap 'wata727/tflint'

##
## Strongly Recommended
##
## Not necessarily required for functionality, but unclear if things will work
## without these upgrades
##

brew 'wget'

# Install GNU core utilities (those that come with macOS are outdated).
# Don't forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew 'coreutils'
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
brew 'findutils'
# Install GNU `sed`, overwriting the built-in `sed`.
brew 'gnu-sed'

##
## Recommended
##
## You can probably do without these, but without a specific reason to skip
## them, they should probably stay
##

# Install more recent versions of some macOS tools.
brew 'grep'
brew 'git'
brew 'make'
brew 'screen'
brew 'vim'

# Support large file with git
brew 'git-lfs'

##
## AWS Tools
##

brew 'awscli'
cask 'aws-vault'
brew 'chamber'


##
## User
##
## Put your packages here
##

cask '1password'
cask '1password-cli'
cask 'docker'
cask 'fork'
cask 'firefox'
brew 'gh'
cask 'gitup'
cask 'gpg-suite'
cask 'grandperspective'
brew 'httpie'
cask 'keybase'
brew 'java'
cask 'ngrok'
cask 'notion'
cask 'obsidian'
brew 'shellcheck'
brew 'terraform'
brew 'tflint'
brew 'tree'
cask 'visual-studio-code'
cask 'vlc'
brew 'watch'
cask 'xquartz'

# Install language interpreters
brew 'python'

# Install App Store packages
# for some reason, Keynote, Numbers, and Pages insist on being reinstalled on
# every run, so, for the time being, they've been disabled.
# mas 'Keynote', id: 409_183_694
# mas 'Numbers', id: 409_203_825
# mas 'Pages', id: 409_201_541
mas 'Magnet', id: 441_258_766
mas 'Pocket', id: 568_494_494
mas 'Slack', id: 803_453_959

# Install zsh
brew 'zsh'
brew 'zsh-completions'

# Enough libraries just assume watchman is installed, we might as well just have
# it by default
brew 'watchman'
