# Not including in `all` because many companies may install it through MDM and
# I don't want to clobber that
cask 'zoom'

cask 'quicken'
cask 'steam'
cask 'spideroakone'

mas 'Byword', id: 420_212_497
mas 'Evernote', id: 406_056_744
